### ISSUE TITLE
Lack of support for simlinks

### ISSUE THREAD

**Issue by blackd** [imgbot/Imgbot#1237]
in this pull request https://github.com/blackd/Inventory-Profiles/pull/197 imgbot didn't detect that /platforms/*/src/shared/ are simlinks to the same dir and processed the images as separate.
Also it didn't detect the real image in shared-sources/....

**Comment by GrigoreMihai** [comment]
Hello, sorry for the late reply, it is the expected behaviour to print the optimization for symlinks (just the stats without adding any images), but it will only optimize the original image. I see from the pr that it optimized the original image from here: https://github.com/blackd/Inventory-Profiles/blob/fe67d0adc2483a950a8c182e888ad0e18d8b23e5/common/src/main/resources/assets/inventoryprofilesnext/textures/gui/gui_buttons.png and only added the symlinks in the optimization report. Let me know if I missed anything here?

**Comment by blackd** [comment]
oh I understand
